[package]
name = "rust_ahk_dll"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_System",
    "Win32_System_LibraryLoader",
] }
encoding_rs = "0.8.33"
widestring = "1.2.1"
